name: pucesm_app

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  image_cropper: ^9.0.0
  webview_flutter: ^4.10.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Para generar el ícono de la app (Android)

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo_puce.png
    - assets/images/logo_puce.png
    - assets/splash/logo_white.png

# Configuración de iconos de la app
flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/logo_puce.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/logo_puce.png

# Configuración de pantalla de inicio (splash screen)
flutter_native_splash:
  color: "#1E63FF"
  image: assets/splash/logo_white.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#1E63FF"
    image: assets/splash/logo_white.png


